version: "3"

services:
  nodejs:
    image: rest-app
    restart: on-failure # restart the app if app fails to start
    build:  # looking for Dockerfile in "./app" to build this "nodejs" image
      context: ./app
      dockerfile: Dockerfile
    depends_on: # indicate "db" service should be executed first 
      - db
    ports:
      - "4000:4000" # map host port 4000 to container port 4000
    entrypoint: ["/wait.sh"] # In case "depends_on" not work, use this shell script to control the service execution order
                              # "entrypoint" keyword: to execute the shell script file, i.e., wait.sh.

  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "33000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "00000000"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
